=== INFORMACION DEL SISTEMA ===
Fecha: 2025-09-24 11:01:20
Nombre del PC: T140J2312077877
Usuario: 56384284

=== SISTEMA OPERATIVO ===
SO: Microsoft Windows 10 Pro
Version: 10.0.19045
Arquitectura: 64 bits

=== HARDWARE ===
Fabricante: JP-IK
Modelo: T140J_Sargas_2024
Numero de Serie: YKT140J2312077877
Procesador: Intel(R) Celeron(R) N4500 @ 1.10GHz
Nucleos: 2
Hilos: 2
RAM Total: 7.78 GB
RAM Libre: 3.9 GB
Uso de RAM: 49.87%
Disco Total (C:): 115.84 GB
Disco Libre (C:): 55.46 GB
Uso de Disco: 52.12%

=== RED ===
Direccion IP: 192.168.2.124
Gateway: 192.168.2.1
DNS Servers: 192.168.2.1
Conexion LAN: False
Conexion WAN: True
Conexion DNS: True

=== PERIFERICOS CONECTADOS ===
Teclado: Mejorado (101 ó 102 teclas) - Conectado
Teclado: Mejorado (101 ó 102 teclas) - Conectado
Teclado: Mejorado (101 ó 102 teclas) - Conectado
Teclado: Mejorado (101 ó 102 teclas) - Conectado
Raton: Dispositivo de entrada USB - Conectado
Raton: Mouse compatible con HID - Conectado
Monitor: Monitor PnP genérico - Conectado
Impresora: OneNote for Windows 10 - Conectada
Impresora: Microsoft XPS Document Writer - Conectada
Impresora: Microsoft Print to PDF - Conectada
Impresora: Fax - Conectada
